package com.example.gallery2.utils

object Constants {
    const val BASE_URL = "http://gallery.dev.webant.ru/"
    const val NAME_APP_PREFERENCE = "settings"
    const val APP_PREFERENCE_EMAIL = "email"
    const val APP_PREFERENCE_ID = "id"
    const val APP_PREFERENCE_USER_ID = "user_id"
    const val APP_PREFERENCE_SECRET = "secret"
    const val APP_PREFERENCE_PASSWORD = "password"
    const val APP_PREFERENCE_LOGIN_TOKEN = "login_token"
    const val APP_PREFERENCE_REFRESH_TOKEN = "refresh_token"
    const val ARG_TABS = "tab_counter"
    const val BASE_URL_MEDIA = "http://gallery.dev.webant.ru/media/"
    const val BACK_PRESSED = "Press Again to Exit"
    const val BUNDLE_PHOTO_ID = "photo_id"
    const val ERROR_CONNECTION = "Connection error,\\n please try again"
    const val NO_DATA = "No Data"
    const val PHOTO_URI = "photo_uri"
    const val UPLOAD_PHOTO_SUCCESS = "Publication has been moderated"
    const val TOAST_PERMISSION_CAMERA = "For adding photo \n you must give access to camera"
    const val TOAST_PERMISSION_STORAGE = "For adding photo \n you must give access to storage"
    const val TOAST_USER_INFO_UPDATED = "Profile update success"
    const val TOAST_USER_NULL_FIELDS = "Fields with * must be not null"
    const val TOAST_USER_NULL_FIELDS_SETTINGS = "Fields must be not null"
    const val TOAST_USER_DIFFERENT_PASSWORDS = "Passwords are different"
    const val TOAST_USER_WRONG_OLD_PASSWORD = "Wrong old password! \n Password not update!"
    const val TOAST_USER_PASSWORD_UPDATED = "Password updated!"
    const val TOAST_USER_NOT_VALID_EMAIL = "Wrong type of Email"
    const val TOAST_USER_NOT_VALID_PAIR_EMAIL_PASSWORD = "Wrong login or password"
    const val TOAST_USER_REGISTRATION_SUCCESS = "Registration success"
}